"""Add middle_name to User and make phone required

Revision ID: 2026_05_19_0000_add_middle_name_and_make_phone_required
Revises:
Create Date: 2026-05-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2026_05_19_0000_add_middle_name_and_make_phone_required'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               nullable=True)
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###